
<!-- The Introductions Page -->

<div id="introduction" class="page">
    <div>
        <p class="header">Hello, I am Johnny Chen</p>
        <div class="seperator"></div>
        <div id="desc">
            <p>Currently, I am a student studying Computer Science @ RPI '27. </p>
            <p>My main area of focus currently is AL/ML. I also enjoy UI/UX and Game Design as other hobbies.</p>
        </div>
    </div>
    <div class="seperator"></div>
    <div>
        <button class="btn-important">Contact Me</button>
    </div>
</div>