<div id="curtain-menu">
    <div class="curtain-content">
        <a href="#">About</a>
        <a href="#">My Work</a>
        <a href="#">Contact</a>
        <a href="#">Blog</a>
    </div>

    <a id="close-curtain" onclick="raiseCurtain()">&times;</a>
</div>

<img id="open-curtain" src="./resources/images/site/menu/greenhamburger.png" onclick="dropCurtain()">

<div id="social-container">
    <ul id="socials">
        <li id="github"><img src="./resources/images/site/contact-icons/github-mark.png" alt="github logo"><a href="" target="_blank"></a></li>
        <li><img><a href="" target="_blank"></a></li>
        <li><img><a href="" target="_blank"></a></li>
    </ul>
</div>