<div id="curtain-menu">
    <div class="curtain-content">
        <a href="#">About</a>
        <a href="#">My Work</a>
        <a href="#">Contact</a>
    </div>

    <a id="close-curtain" onclick="raiseCurtain()">&times;</a>
</div>

<img id="open-curtain" src="./resources/images/site/menu/greenhamburger.png" onclick="dropCurtain()" alt="Picture of a Hamburger Menu Icon">

<div id="social-container">
    <ul id="socials">
        <li id="github"><a href="https://github.com/chenjohnny-cs" target="_blank"><img src="./resources/images/site/contact-icons/github-mark-white.png" alt="github logo"></a></li>
        <li id="linkedin"><a href="https://www.linkedin.com/in/junyu-chen-301417218/" target="_blank"><img src="./resources/images/site/contact-icons/In-White-48.png" alt="linkedin logo"></a></li>
    </ul>
</div>